=== pedromxavier/QUBOLibData.jl/scripts/metadata.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "QUBO Instance Metadata Schema",
    "type": "object",
    "required": [
        "code",
        "size",
        "format",
        "problem"
    ],
    "properties": {
        "code": {
            "type": "string",
            "minLength": 1
        },
        "size": {
            "type": "integer"
        },
        "format": {
            "type": "string",
            "enum": [
                "qubo",
                "qubist",
                "bpqjson",
                "minizinc",
                "hfs"
            ]
        },
        "problem": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "3R3X",
                        "5R5X"
                    ]
                },
                "sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "source": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "minLength": 1
                    },
                    "author": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "minLength": 1
                        },
                        "minLength": 1
                    },
                    "year": {
                        "type": "integer"
                    },
                    "citekey": {
                        "type": "string",
                        "minLength": 1
                    }
                }
            }
        }
    }
}

=== pedromxavier/QUBOLibData.jl/collections/arXiv_2103_08464_3r3x/metadata.json
{
    "code": "arXiv_2103_08464_3r3x",
    "size": 2301,
    "format": "qubist",
    "problem": {
        "type": "3R3X",
        "sizes": [
            16,
            32,
            48,
            64,
            80,
            96,
            112,
            128,
            144,
            160,
            176,
            192,
            208,
            224,
            384,
            400,
            416,
            432,
            448,
            512,
            1024,
            2048,
            4096
        ]
    },
    "source": [
        {
            "type": "online",
            "citekey": "kowalsky:2022:data",
            "title": "3R3X instances for '3-Regular 3-XORSAT Planted Solutions Benchmark of Classical and Quantum Heuristic Optimizers'",
            "author": [
                "Matthew Kowalsky",
                "Tameem Albash",
                "Itay Hen",
                "Daniel A. Lidar"
            ],
            "year": 2022,
            "url": "https://unmm-my.sharepoint.com/:u:/g/personal/talbash_unm_edu/EZuSjxn4So9BsTBzKazxuA0B6A72AezCeZj2fnks4lqt5Q?e=euft6M",
            "urldate": "2023-04-06"
        },
        {
            "type": "article",
            "citekey": "kowalsky:2022",
            "title": "3-Regular 3-XORSAT Planted Solutions Benchmark of Classical and Quantum Heuristic Optimizers",
            "author": [
                "Matthew Kowalsky",
                "Tameem Albash",
                "Itay Hen",
                "Daniel A. Lidar"
            ],
            "year": 2022,
            "doi": "10.1088/2058-9565/ac4d1b",
            "url": "https://doi.org/10.1088%2F2058-9565%2Fac4d1b",
            "journal": "Quantum Science and Technology"
        }
    ]
}

=== pedromxavier/QUBOLibData.jl/collections/arXiv_1903_10928_3r3x/metadata.json
{
    "code": "arXiv_1903_10928_3r3x",
    "size": 3202,
    "format": "qubist",
    "problem": {
        "type": "3R3X",
        "sizes": []
    },
    "source": [
        {
            "type": "online",
            "citekey": "hen:2019:data",
            "title": "3R3X instances for 'Equation Planting: A Tool for Benchmarking Ising Machines'",
            "author": [
                "Itay Hen"
            ],
            "year": 2019,
            "url": "https://sites.usc.edu/itayhen/files/2019/09/3r3x.zip",
            "urldate": "2023-04-06"
        },
        {
            "doi": "0.1103/physrevapplied.12.011003",
            "url": "https://doi.org/10.1103%2Fphysrevapplied.12.011003",
            "year": 2019,
            "citekey": "hen:2019",
            "month": "jul",
            "publisher": "American Physical Society ({APS})",
            "volume": "12",
            "number": "1",
            "author": [
                "Itay Hen"
            ],
            "title": "Equation Planting: A Tool for Benchmarking Ising Machines",
            "journal": "Physical Review Applied"
        }
    ]
}
